Add default response
mattherman/MbDotNet pull request #87
Opened 2020-08-06 13:56 UTC by KichiginaTatiana

https://github.com/mattherman/MbDotNet/issues/64

2020-08-24 13:23 UTC, mattherman requested changes
Just a couple small changes + the merge conflicts, but then it should be good to go

2020-08-24 13:23 UTC, mattherman commented on MbDotNet/Models/Imposters/HttpImposter.cs
> +        public HttpResponseFields DefaultResponse { get; set; }
Please make this a `private set` on each imposter type to be consistent with the other properties.

2020-08-24 13:23 UTC, mattherman commented on mb.pid
> +85932
Remove this file, and if you want you could add `mb.pid` and `mb.log` to the `.gitignore`.

2020-08-25 16:13 UTC, mattherman commented on MbDotNet/Models/Imposters/RetrievedImposter.cs
> +    public abstract class RetrievedImposter<TRequest, TResponseFields, TDefaultResponse>
Is there ever a situation where `TResponseFields` will be different from `TDefaultResponse`? I think we can support this feature without adding an additional generic type parameter.

2020-08-26 15:07 UTC, mattherman approved these changes

2020-08-26 15:08 UTC, merged

2020-08-26 15:37 UTC, mattherman commented
I've published new packages that include all four of your changes:
* https://www.nuget.org/packages/MbDotNet/4.3.3
* https://www.nuget.org/packages/MbDotNet/5.0.0-rc6

They should be available soon. Thanks again!

2020-08-27 05:30 UTC, KichiginaTatiana commented
> I've published new packages that include all four of your changes:
> 
> * https://www.nuget.org/packages/MbDotNet/4.3.3
> * https://www.nuget.org/packages/MbDotNet/5.0.0-rc6
> 
> They should be available soon. Thanks again!

thanks!